### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by longhotsummer** [Code4SA/best-practices#6]
We should have a launch checklist for new projects, with things like:

- [ ] is there a `foo.code4sa.org` domain name? Don't use foo.herokuapp.com.
- [ ] is new relic installed and running for the app?
- [ ] if you set up a new server, is new relic installed and running on the server?
- [ ] should the site be mobile friendly? Is it?
